import { Inter} from "next/font/google";
import "./globals.css";


const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "Wealthify AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} `}> 
        
        {/*header*/}
        <header />
        
        {/*footer */} 
        <footer className="bg-blue-50 py-12">
        <div className="container mx-auto text-center px-4 text-gray-500">
          <p>Made with ❤️ by Wealthify</p>
        </div>
        </footer>
       
        
        </body>
    </html>
  );
}
